# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jonaszell/Developer/tblgen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jonaszell/Developer/tblgen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonaszell/Developer/tblgen/CMakeFiles /Users/jonaszell/Developer/tblgen//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonaszell/Developer/tblgen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tblgen

# Build rule for target.
tblgen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tblgen
.PHONY : tblgen

# fast build rule for target.
tblgen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/build
.PHONY : tblgen/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/main.cpp.s
.PHONY : main.cpp.s

src/Backend/EmitClassHierarchy.o: src/Backend/EmitClassHierarchy.cpp.o
.PHONY : src/Backend/EmitClassHierarchy.o

# target to build an object file
src/Backend/EmitClassHierarchy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Backend/EmitClassHierarchy.cpp.o
.PHONY : src/Backend/EmitClassHierarchy.cpp.o

src/Backend/EmitClassHierarchy.i: src/Backend/EmitClassHierarchy.cpp.i
.PHONY : src/Backend/EmitClassHierarchy.i

# target to preprocess a source file
src/Backend/EmitClassHierarchy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Backend/EmitClassHierarchy.cpp.i
.PHONY : src/Backend/EmitClassHierarchy.cpp.i

src/Backend/EmitClassHierarchy.s: src/Backend/EmitClassHierarchy.cpp.s
.PHONY : src/Backend/EmitClassHierarchy.s

# target to generate assembly for a file
src/Backend/EmitClassHierarchy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Backend/EmitClassHierarchy.cpp.s
.PHONY : src/Backend/EmitClassHierarchy.cpp.s

src/Backend/PrintRecords.o: src/Backend/PrintRecords.cpp.o
.PHONY : src/Backend/PrintRecords.o

# target to build an object file
src/Backend/PrintRecords.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Backend/PrintRecords.cpp.o
.PHONY : src/Backend/PrintRecords.cpp.o

src/Backend/PrintRecords.i: src/Backend/PrintRecords.cpp.i
.PHONY : src/Backend/PrintRecords.i

# target to preprocess a source file
src/Backend/PrintRecords.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Backend/PrintRecords.cpp.i
.PHONY : src/Backend/PrintRecords.cpp.i

src/Backend/PrintRecords.s: src/Backend/PrintRecords.cpp.s
.PHONY : src/Backend/PrintRecords.s

# target to generate assembly for a file
src/Backend/PrintRecords.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Backend/PrintRecords.cpp.s
.PHONY : src/Backend/PrintRecords.cpp.s

src/Basic/FileManager.o: src/Basic/FileManager.cpp.o
.PHONY : src/Basic/FileManager.o

# target to build an object file
src/Basic/FileManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Basic/FileManager.cpp.o
.PHONY : src/Basic/FileManager.cpp.o

src/Basic/FileManager.i: src/Basic/FileManager.cpp.i
.PHONY : src/Basic/FileManager.i

# target to preprocess a source file
src/Basic/FileManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Basic/FileManager.cpp.i
.PHONY : src/Basic/FileManager.cpp.i

src/Basic/FileManager.s: src/Basic/FileManager.cpp.s
.PHONY : src/Basic/FileManager.s

# target to generate assembly for a file
src/Basic/FileManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Basic/FileManager.cpp.s
.PHONY : src/Basic/FileManager.cpp.s

src/Basic/FileUtils.o: src/Basic/FileUtils.cpp.o
.PHONY : src/Basic/FileUtils.o

# target to build an object file
src/Basic/FileUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Basic/FileUtils.cpp.o
.PHONY : src/Basic/FileUtils.cpp.o

src/Basic/FileUtils.i: src/Basic/FileUtils.cpp.i
.PHONY : src/Basic/FileUtils.i

# target to preprocess a source file
src/Basic/FileUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Basic/FileUtils.cpp.i
.PHONY : src/Basic/FileUtils.cpp.i

src/Basic/FileUtils.s: src/Basic/FileUtils.cpp.s
.PHONY : src/Basic/FileUtils.s

# target to generate assembly for a file
src/Basic/FileUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Basic/FileUtils.cpp.s
.PHONY : src/Basic/FileUtils.cpp.s

src/Basic/IdentifierInfo.o: src/Basic/IdentifierInfo.cpp.o
.PHONY : src/Basic/IdentifierInfo.o

# target to build an object file
src/Basic/IdentifierInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Basic/IdentifierInfo.cpp.o
.PHONY : src/Basic/IdentifierInfo.cpp.o

src/Basic/IdentifierInfo.i: src/Basic/IdentifierInfo.cpp.i
.PHONY : src/Basic/IdentifierInfo.i

# target to preprocess a source file
src/Basic/IdentifierInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Basic/IdentifierInfo.cpp.i
.PHONY : src/Basic/IdentifierInfo.cpp.i

src/Basic/IdentifierInfo.s: src/Basic/IdentifierInfo.cpp.s
.PHONY : src/Basic/IdentifierInfo.s

# target to generate assembly for a file
src/Basic/IdentifierInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Basic/IdentifierInfo.cpp.s
.PHONY : src/Basic/IdentifierInfo.cpp.s

src/Lex/Lexer.o: src/Lex/Lexer.cpp.o
.PHONY : src/Lex/Lexer.o

# target to build an object file
src/Lex/Lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Lex/Lexer.cpp.o
.PHONY : src/Lex/Lexer.cpp.o

src/Lex/Lexer.i: src/Lex/Lexer.cpp.i
.PHONY : src/Lex/Lexer.i

# target to preprocess a source file
src/Lex/Lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Lex/Lexer.cpp.i
.PHONY : src/Lex/Lexer.cpp.i

src/Lex/Lexer.s: src/Lex/Lexer.cpp.s
.PHONY : src/Lex/Lexer.s

# target to generate assembly for a file
src/Lex/Lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Lex/Lexer.cpp.s
.PHONY : src/Lex/Lexer.cpp.s

src/Lex/Token.o: src/Lex/Token.cpp.o
.PHONY : src/Lex/Token.o

# target to build an object file
src/Lex/Token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Lex/Token.cpp.o
.PHONY : src/Lex/Token.cpp.o

src/Lex/Token.i: src/Lex/Token.cpp.i
.PHONY : src/Lex/Token.i

# target to preprocess a source file
src/Lex/Token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Lex/Token.cpp.i
.PHONY : src/Lex/Token.cpp.i

src/Lex/Token.s: src/Lex/Token.cpp.s
.PHONY : src/Lex/Token.s

# target to generate assembly for a file
src/Lex/Token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Lex/Token.cpp.s
.PHONY : src/Lex/Token.cpp.s

src/Message/Diagnostics.o: src/Message/Diagnostics.cpp.o
.PHONY : src/Message/Diagnostics.o

# target to build an object file
src/Message/Diagnostics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Message/Diagnostics.cpp.o
.PHONY : src/Message/Diagnostics.cpp.o

src/Message/Diagnostics.i: src/Message/Diagnostics.cpp.i
.PHONY : src/Message/Diagnostics.i

# target to preprocess a source file
src/Message/Diagnostics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Message/Diagnostics.cpp.i
.PHONY : src/Message/Diagnostics.cpp.i

src/Message/Diagnostics.s: src/Message/Diagnostics.cpp.s
.PHONY : src/Message/Diagnostics.s

# target to generate assembly for a file
src/Message/Diagnostics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Message/Diagnostics.cpp.s
.PHONY : src/Message/Diagnostics.cpp.s

src/Message/DiagnosticsEngine.o: src/Message/DiagnosticsEngine.cpp.o
.PHONY : src/Message/DiagnosticsEngine.o

# target to build an object file
src/Message/DiagnosticsEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Message/DiagnosticsEngine.cpp.o
.PHONY : src/Message/DiagnosticsEngine.cpp.o

src/Message/DiagnosticsEngine.i: src/Message/DiagnosticsEngine.cpp.i
.PHONY : src/Message/DiagnosticsEngine.i

# target to preprocess a source file
src/Message/DiagnosticsEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Message/DiagnosticsEngine.cpp.i
.PHONY : src/Message/DiagnosticsEngine.cpp.i

src/Message/DiagnosticsEngine.s: src/Message/DiagnosticsEngine.cpp.s
.PHONY : src/Message/DiagnosticsEngine.s

# target to generate assembly for a file
src/Message/DiagnosticsEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Message/DiagnosticsEngine.cpp.s
.PHONY : src/Message/DiagnosticsEngine.cpp.s

src/Parser.o: src/Parser.cpp.o
.PHONY : src/Parser.o

# target to build an object file
src/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Parser.cpp.o
.PHONY : src/Parser.cpp.o

src/Parser.i: src/Parser.cpp.i
.PHONY : src/Parser.i

# target to preprocess a source file
src/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Parser.cpp.i
.PHONY : src/Parser.cpp.i

src/Parser.s: src/Parser.cpp.s
.PHONY : src/Parser.s

# target to generate assembly for a file
src/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Parser.cpp.s
.PHONY : src/Parser.cpp.s

src/Record.o: src/Record.cpp.o
.PHONY : src/Record.o

# target to build an object file
src/Record.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Record.cpp.o
.PHONY : src/Record.cpp.o

src/Record.i: src/Record.cpp.i
.PHONY : src/Record.i

# target to preprocess a source file
src/Record.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Record.cpp.i
.PHONY : src/Record.cpp.i

src/Record.s: src/Record.cpp.s
.PHONY : src/Record.s

# target to generate assembly for a file
src/Record.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Record.cpp.s
.PHONY : src/Record.cpp.s

src/Support/DynamicLibrary.o: src/Support/DynamicLibrary.cpp.o
.PHONY : src/Support/DynamicLibrary.o

# target to build an object file
src/Support/DynamicLibrary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Support/DynamicLibrary.cpp.o
.PHONY : src/Support/DynamicLibrary.cpp.o

src/Support/DynamicLibrary.i: src/Support/DynamicLibrary.cpp.i
.PHONY : src/Support/DynamicLibrary.i

# target to preprocess a source file
src/Support/DynamicLibrary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Support/DynamicLibrary.cpp.i
.PHONY : src/Support/DynamicLibrary.cpp.i

src/Support/DynamicLibrary.s: src/Support/DynamicLibrary.cpp.s
.PHONY : src/Support/DynamicLibrary.s

# target to generate assembly for a file
src/Support/DynamicLibrary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Support/DynamicLibrary.cpp.s
.PHONY : src/Support/DynamicLibrary.cpp.s

src/Support/Format.o: src/Support/Format.cpp.o
.PHONY : src/Support/Format.o

# target to build an object file
src/Support/Format.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Support/Format.cpp.o
.PHONY : src/Support/Format.cpp.o

src/Support/Format.i: src/Support/Format.cpp.i
.PHONY : src/Support/Format.i

# target to preprocess a source file
src/Support/Format.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Support/Format.cpp.i
.PHONY : src/Support/Format.cpp.i

src/Support/Format.s: src/Support/Format.cpp.s
.PHONY : src/Support/Format.s

# target to generate assembly for a file
src/Support/Format.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Support/Format.cpp.s
.PHONY : src/Support/Format.cpp.s

src/Support/LiteralParser.o: src/Support/LiteralParser.cpp.o
.PHONY : src/Support/LiteralParser.o

# target to build an object file
src/Support/LiteralParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Support/LiteralParser.cpp.o
.PHONY : src/Support/LiteralParser.cpp.o

src/Support/LiteralParser.i: src/Support/LiteralParser.cpp.i
.PHONY : src/Support/LiteralParser.i

# target to preprocess a source file
src/Support/LiteralParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Support/LiteralParser.cpp.i
.PHONY : src/Support/LiteralParser.cpp.i

src/Support/LiteralParser.s: src/Support/LiteralParser.cpp.s
.PHONY : src/Support/LiteralParser.s

# target to generate assembly for a file
src/Support/LiteralParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Support/LiteralParser.cpp.s
.PHONY : src/Support/LiteralParser.cpp.s

src/TableGen.o: src/TableGen.cpp.o
.PHONY : src/TableGen.o

# target to build an object file
src/TableGen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/TableGen.cpp.o
.PHONY : src/TableGen.cpp.o

src/TableGen.i: src/TableGen.cpp.i
.PHONY : src/TableGen.i

# target to preprocess a source file
src/TableGen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/TableGen.cpp.i
.PHONY : src/TableGen.cpp.i

src/TableGen.s: src/TableGen.cpp.s
.PHONY : src/TableGen.s

# target to generate assembly for a file
src/TableGen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/TableGen.cpp.s
.PHONY : src/TableGen.cpp.s

src/TemplateParser.o: src/TemplateParser.cpp.o
.PHONY : src/TemplateParser.o

# target to build an object file
src/TemplateParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/TemplateParser.cpp.o
.PHONY : src/TemplateParser.cpp.o

src/TemplateParser.i: src/TemplateParser.cpp.i
.PHONY : src/TemplateParser.i

# target to preprocess a source file
src/TemplateParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/TemplateParser.cpp.i
.PHONY : src/TemplateParser.cpp.i

src/TemplateParser.s: src/TemplateParser.cpp.s
.PHONY : src/TemplateParser.s

# target to generate assembly for a file
src/TemplateParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/TemplateParser.cpp.s
.PHONY : src/TemplateParser.cpp.s

src/Type.o: src/Type.cpp.o
.PHONY : src/Type.o

# target to build an object file
src/Type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Type.cpp.o
.PHONY : src/Type.cpp.o

src/Type.i: src/Type.cpp.i
.PHONY : src/Type.i

# target to preprocess a source file
src/Type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Type.cpp.i
.PHONY : src/Type.cpp.i

src/Type.s: src/Type.cpp.s
.PHONY : src/Type.s

# target to generate assembly for a file
src/Type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Type.cpp.s
.PHONY : src/Type.cpp.s

src/Value.o: src/Value.cpp.o
.PHONY : src/Value.o

# target to build an object file
src/Value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Value.cpp.o
.PHONY : src/Value.cpp.o

src/Value.i: src/Value.cpp.i
.PHONY : src/Value.i

# target to preprocess a source file
src/Value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Value.cpp.i
.PHONY : src/Value.cpp.i

src/Value.s: src/Value.cpp.s
.PHONY : src/Value.s

# target to generate assembly for a file
src/Value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tblgen.dir/build.make CMakeFiles/tblgen.dir/src/Value.cpp.s
.PHONY : src/Value.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tblgen"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Backend/EmitClassHierarchy.o"
	@echo "... src/Backend/EmitClassHierarchy.i"
	@echo "... src/Backend/EmitClassHierarchy.s"
	@echo "... src/Backend/PrintRecords.o"
	@echo "... src/Backend/PrintRecords.i"
	@echo "... src/Backend/PrintRecords.s"
	@echo "... src/Basic/FileManager.o"
	@echo "... src/Basic/FileManager.i"
	@echo "... src/Basic/FileManager.s"
	@echo "... src/Basic/FileUtils.o"
	@echo "... src/Basic/FileUtils.i"
	@echo "... src/Basic/FileUtils.s"
	@echo "... src/Basic/IdentifierInfo.o"
	@echo "... src/Basic/IdentifierInfo.i"
	@echo "... src/Basic/IdentifierInfo.s"
	@echo "... src/Lex/Lexer.o"
	@echo "... src/Lex/Lexer.i"
	@echo "... src/Lex/Lexer.s"
	@echo "... src/Lex/Token.o"
	@echo "... src/Lex/Token.i"
	@echo "... src/Lex/Token.s"
	@echo "... src/Message/Diagnostics.o"
	@echo "... src/Message/Diagnostics.i"
	@echo "... src/Message/Diagnostics.s"
	@echo "... src/Message/DiagnosticsEngine.o"
	@echo "... src/Message/DiagnosticsEngine.i"
	@echo "... src/Message/DiagnosticsEngine.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/Record.o"
	@echo "... src/Record.i"
	@echo "... src/Record.s"
	@echo "... src/Support/DynamicLibrary.o"
	@echo "... src/Support/DynamicLibrary.i"
	@echo "... src/Support/DynamicLibrary.s"
	@echo "... src/Support/Format.o"
	@echo "... src/Support/Format.i"
	@echo "... src/Support/Format.s"
	@echo "... src/Support/LiteralParser.o"
	@echo "... src/Support/LiteralParser.i"
	@echo "... src/Support/LiteralParser.s"
	@echo "... src/TableGen.o"
	@echo "... src/TableGen.i"
	@echo "... src/TableGen.s"
	@echo "... src/TemplateParser.o"
	@echo "... src/TemplateParser.i"
	@echo "... src/TemplateParser.s"
	@echo "... src/Type.o"
	@echo "... src/Type.i"
	@echo "... src/Type.s"
	@echo "... src/Value.o"
	@echo "... src/Value.i"
	@echo "... src/Value.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

